export const menuItems = [
  { id: 'image-format', icon: '🖼️', label: '图片格式转换', active: true },
  { id: 'json-tools', icon: '📝', label: 'JSON 工具', active: true },
  { id: 'timestamp', icon: '⏰', label: '时间戳转换', active: true },
  { id: 'base64', icon: '🔐', label: 'Base64 编解码', active: true },
  { id: 'url', icon: '🔗', label: 'URL 编解码', active: true },
  // { id: 'calculator', icon: '🔢', label: '计算器', active: true },
  { id: 'base-converter', icon: '🔣', label: '进制转换', active: true },
  { id: 'power-of-two', icon: '2️⃣', label: '2 的次方', active: true },
  { id: 'key-generator', icon: '🔑', label: '密钥生成器', active: true },
  // { id: 'sql-converter', icon: '🔄', label: 'SQL 转换器', active: true },
  // { id: 'image-compress', icon: '📦', label: '图片压缩', disabled: true },
  // { id: 'image-resize', icon: '📐', label: '图片裁剪', disabled: true },
  // { id: 'image-watermark', icon: '💧', label: '图片水印', disabled: true },
  // { id: 'pdf-convert', icon: '📄', label: 'PDF转换', disabled: true },
  // { id: 'video-convert', icon: '🎬', label: '视频转换', disabled: true },
];
